### ISSUE TITLE
App importing conmat .csv as long string

### ISSUE THREAD

**Issue by bacaron** [filipinascimento/bl-network-measurements#3]
Hey Filipi,

Thank you for all your hard work on creating network science apps on BL.

I recently created an app to use MRTrix3's tck2connectome functionality to generate adjacency matrices from streamline data. I've converted the data to a conmat datatype and tried running this app. I unfortunately got this error:

Traceback (most recent call last):
  File "/export/prod/5f2a1bfea5b64365c4a2c220/5f2b1514a5b6433f20a31544/main.py", line 330, in <module>
    adjacencyMatrix = np.abs(loadCSVMatrix(PJ(CSVDirectory, filename))) #taking the ABS temporarily
  File "/export/prod/5f2a1bfea5b64365c4a2c220/5f2b1514a5b6433f20a31544/main.py", line 238, in loadCSVMatrix
    return np.loadtxt(filename,delimiter=",")
  File "/usr/local/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1159, in loadtxt
    for x in read_data(_loadtxt_chunksize):
  File "/usr/local/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1087, in read_data
    items = [conv(val) for (conv, val) in zip(converters, vals)]
  File "/usr/local/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1087, in <listcomp>
    items = [conv(val) for (conv, val) in zip(converters, vals)]
  File "/usr/local/lib/python3.7/site-packages/numpy/lib/npyio.py", line 794, in floatconv
    return float(x)
ValueError: could not convert string to float: '0 4.826602929839489e-05 0.0001561885430036407 0.0001666640132600862 5.939118303358555e-05 9.410787804575936e-05 8.81614497829057e-05 0.0001794734426463644...' (the rest of the values are included in the line in the error log but I removed them for brevity).

I was running into a similar issue loading in the .csv into python for some things. I'm wondering if there's some weird issue with the way MRTrix3 saves the csv files. [cm.zip](https://github.com/filipinascimento/bl-network-measurements/files/5031007/cm.zip)

I've attached the conmat data here for debugging purposes.

Thank you,
Brad

**Comment by bacaron** [comment]
I figured out how to fix it on my end. MRTrix3 appears to output csvs with a space delimiter instead of a comma. Easy fix on my end.

I'm closing this issue.
